<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum backend
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */ 
$dayname = array(
    '1' => 'Montag',
    '2' => 'Dienstag',
    '3' => 'Mittwoch',
    '4' => 'Donnerstag',
    '5' => 'Freitag',
    '6' => 'Samstag',
    '7' => 'Sonntag'
);
//$datetime = new \DateTime();
// $this->dateFormat
?>
<div id="dashboardrow" class="row">
	<div class="medium-6 columns">
		<h2><?php echo $this->content['headline']; ?></h2>
		<?php 
		if ( isset($this->content['content']) && strlen($this->content['content']) > 1 ){
		    echo $this->content['content'];
		}
		?>
	</div>
	<div class="medium-6 columns">
		<div class="right">
		
			<ul class="stats">
				<li class="peter-river"><a href="/mcwork/article"><i class="fa fa-file-text-o"></i></a>
					<div class="details"><a href="/mcwork/article">
						<span class="big">Blogs, Nachrichten</span>
						<span>bearbeiten</span></a>
					</div></li>
			</ul>			
		
			<ul class="stats">
				<li class="midnight-blue"><a href="/mcwork/contribution"><i class="fa fa-pencil"></i></a>
					<div class="details"><a href="/mcwork/contribution">
						<span class="big">Beiträge</span>
						<span>bearbeiten</span></a>
					</div></li>
			</ul>				
		
			<ul class="stats">
				<li class="pomegranate"><i class="fa fa-calendar"></i>
					<div class="details">
						<span class="big"><?php echo $this->datetimeformat()  ?></span>
						<span><?php echo $dayname[date('N')]; ?>, <time id="serverClock" datetime=""><?php echo $this->datetimeformat(null,false,'LONG')  ?></time></span>
					</div></li>
			</ul>
			
			
			<ul class="minitiles">
				<li class="carrot"><a href="/" target="_blank"><i class="fa fa-home"></i></a>
				</li>
			</ul>	
			
			<ul class="minitiles">
				<li class="carrot"><a href="https://www.jochum-mediaservices.de/medias/anleitungen/handbuch-contentinum5.pdf" target="_blank"><i class="fa fa-book" aria-hidden="true"> </i></a>
				</li>
			</ul>						

		</div>		
	</div>	
</div>
<hr />
<?php if ('admin' == $this->role){ ?>
<div id="dashboardContent" class="row">
    <div id="addTblContent" class="medium-12 columns">
        <table class="table tblNoSort display compact" id="mcworkTables">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Seitenname</th>
                    <th>Titel</th>
                    <th>#</th>
                    <th class="hide-for-small text-right">Bearbeiten</th>
                </tr>
            </thead>
          <tbody>
          </tbody>
        </table>
    </div>
</div>
<?php } ?>