<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum backend
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */
$src = function($entry, $field = 'thumbnail', $ln = 'mediaLink') {
    $ret = '<figure class="filegroup-element">';
    if ( preg_match('/image\//', $entry->mediaType)  ){
        $src = $entry->mediaLink;
        $ret .= '<img src="' . $src . '" alt="' . $entry->mediaName . '" />'; // width="200"
    } else {
        switch ($entry->mediaType){
            case 'application/pdf' :
                $ret .= '<i class="fa fa-file-pdf-o fa-5x pdf-color"></i>';
                break;
            default:
                $ret .= '<i class="fa fa-file fa-5x"></i>';
                break;
        }
    }
    $ret .= '<figcaption>' . $entry->mediaName . '</figcaption>';
    $ret .= '</figure>';
    return $ret;
};
$entries = array();
$i = 1;
foreach ($this->entries as $entry) {
    if (true === $this->listIsAllowed($entry, $this->identity)){
        $tmp = array();
        $tmp['fileident'] = $entry->id;
        $tmp['file'] = $src($entry->webMediasId);
        $tmp['mediaident'] = $entry->webMediasId->id;
        $entries[$i] = $tmp;
        $i++;        
    }

} 
echo $this->json($entries);
exit();
?>