<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>404 Error - Oops error occurred</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>
<?php 
if ($this->exceptions){
    print '<h1>' . $this->translate('A 500 error occurred') .'</h1>';
    print '<h2>Fehler im Applikationsablauf / A application error</h2>';
    print '<p><strong>Hey, something wrong. we will correct this soon, we promise !</strong></p>';
    print '<h3>Meldung/Messages:<br />';
    print $this->exceptions['message'] . '</h3>';
    print '<p>' . $this->exceptions['message'] . '</p>';
    print '<pre>';
    print $this->exceptions['tracestring'];
    print '</pre>';
} else {
    print '<h1>' . $this->translate('A 404 error occurred') . '</h1>';
    print '<h2>Diese Seite konnte nicht gefunden werden.</h2>';
    print '<h3>Gr&uuml;nde k&ouml;nnten sein, einen veralterten oder falschen Link betätigt oder eine falsche URL aufgerufen zu haben.</h3>';
    print '<h4><a href="/">Hier gelangen Sie zur&uuml;ck zur Startseite.</a></h4>';
}
?>
</body>
</html>