<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>404 Error - Oops error occurred</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>
	<h1><?php echo $this->translate('A 404 error occurred') ?></h1>
	<h2>Diese Seite konnte nicht gefunden werden.</h2>
	<h3>Gr&uuml;nde k&ouml;nnten sein, einen veralterten oder falschen Link betätigt oder eine falsche URL aufgerufen zu haben.</h3>
	<h4><a href="/">Hier gelangen Sie zur&uuml;ck zur Startseite.</a></h4>
</body>
</html>