<?php
use ContentinumComponents\Tools\ConvertMonthDayNames;
$convert = new ConvertMonthDayNames();
$content = '';
$displaymonthname = false;
foreach ($this->entries as $entry) {

    $datetime = new \DateTime($entry['dateStart']);
    $mthNum = $datetime->format('m');
 
    if ($displaymonthname != $mthNum){
        $displaymonthname = $mthNum;
        $content .= $convert->get($mthNum);
        $content .= "\n\n";
    }
    $content .= iconv("UTF-8", "Windows-1252", stripslashes($entry['summary'])) . ";";
    $content .= "\n";    
    if ($entry['organizerId'] > 1) {
        $content .= utf8_decode($entry['organizerName']);
    } elseif (strlen($entry['organizer']) > 1) {
        $content .= utf8_decode($entry['organizer']);
    }  
    if ($entry['accountId'] > 1) {
        $dataLocation = ' ';
        if (strlen($entry['accountStreet']) > 1) {
            $street = $entry['accountStreet'];
            if (strlen($entry['accountStreetNum']) > 0) {
                $street .= ' ' . $entry['accountStreetNum'];
            }
            $dataLocation .= $street;
        }
        if (strlen($entry['accountZipcode']) > 1) {
            $zipcode = $entry['accountZipcode'];
            $dataLocation .= ' ' . $zipcode;
        }
        if (strlen($entry['accountCity']) > 1) {
            $city = $entry['accountCity'];
            $dataLocation .= ' ' . $city;
        }
        $content .= "\n";
        $content .= utf8_decode($entry['accountName'] . $dataLocation);
    } else {
        $zipcode = '';
        $dataLocation = ' ';
        if (strlen($entry['locationAddresse']) > 1) {
            $address = $entry['locationAddresse'];
            $dataLocation .= $address;
        }
        if (strlen($entry['locationZipcode']) > 1) {
            $zipcode = $entry['locationZipcode'];
            $dataLocation .= ' ' . $zipcode;
        }
        if (strlen($entry['locationCity']) > 1) {
            $city = $entry['locationCity'];
            $dataLocation .= ' ' . $city;
        }
        $content .= "\n";
        $content .= utf8_decode($entry['location'] . ' ' . $dataLocation);
    }  
    $dateEndStr = '';
    if ('0000-00-00 00:00:00' !== $entry['dateEnd']){
        
        if ($entry['dateEnd'] !== $entry['dateStart']){
            $dateTimeEnd = new \DateTime($entry['dateEnd']);
            if ($datetime->format("Y-m-d") === $dateTimeEnd->format("Y-m-d")){
                $dateEndStr = ' bis ' . $dateTimeEnd->format("H:i");
            } else {
                $dateEndStr = ' bis ' . $convert->get($dateTimeEnd->format('N'),'dayname')  . ', ' . $dateTimeEnd->format('d') . '. ' . $convert->get($dateTimeEnd->format('m')) . ' ' . $dateTimeEnd->format('Y');
            }
        }
    }    
    
    
    $content .= "\n";
    $content .= $convert->get($datetime->format('N'),'dayname')  . ', ' . $datetime->format('d') . '. ' . $convert->get($datetime->format('m')) . ' ' . $datetime->format('Y');
    if ('00:00' !== $datetime->format("H:i")) {
        $content .= ' ab ' . $datetime->format("H:i") . $dateEndStr . ' Uhr';
    } else {
        $content .= $dateEndStr;
    }    
    
    $content .= "\n\n";
    
}
// download
header("Content-type: application/csv");
header("Content-Disposition: attachment; filename=eventlist-" . date('Y-m-d') . ".csv");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
header("Pragma: public");
echo $content;
exit();
?>