<?php
$xls = 'Gruppenname' . ";";
$xls .= 'Titel' . ";";
$xls .= 'Anrede' . ";";
$xls .= 'Vorname' . ";";
$xls .= 'Name' . ";";
$xls .= 'Jobtitle' . ";";
$xls .= 'Telefon' . ";";
$xls .= 'Telefon Arbeit' . ";";
$xls .= 'Mobil' . ";";
$xls .= 'Fax' . ";";
$xls .= 'E-Mail' . ";";
$xls .= iconv('UTF-8', 'ISO-8859-1', 'Straße') . ";";
$xls .= 'PLZ' . ";";
$xls .= 'Ort' . ";";
$xls .= 'Internet' . ";";
$xls .= "\r\n";
foreach ($this->entries as $entry) {
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->indexGroup->name ) . ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->title ) . ";";
    $name = '';
    if ('mr' == $entry->contacts->salutation){
        $name = 'Herr';
    }
    if ('ms' == $entry->contacts->salutation){
        $name = 'Frau';
    }
    $xls .= $name . ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->firstName) . ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->lastName) . ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->businessTitle) . ";";
    $xls .= $entry->contacts->phoneHome . ";";
    $xls .= $entry->contacts->phoneWork . ";";
    $xls .= $entry->contacts->phoneMobile . ";";
    $xls .= $entry->contacts->phoneFax . ";";
    $xls .= $entry->contacts->contactEmail . ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->contactAddress) . ";";
    $xls .= $entry->contacts->contactZipcode. ";";
    $xls .= iconv('UTF-8', 'ISO-8859-1', $entry->contacts->contactCity) . ";";
    $xls .= $entry->contacts->internet . ";";
    $xls .= "\r\n";
}
header("Content-type: application/csv");
header("Content-Disposition: attachment; filename=exportcontactgroup-" . date('Y-m-d') . ".csv");
header('Cache-Control: max-age=0');
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public');
while (ob_get_level()) {
    ob_end_clean();
}
print $xls;exit();